apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: ap-south-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"
# vpc:
#   private:
#     ap-south-1a:
#       id: subnet-asxcczxxxcxcxz
#   public:
#     ap-south-1c:
# nategateway : Single # HiglyAvailable,Disable

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    labels: { role: workers }
    privateNetworking: true
    availabilityZones: ["ap-south-1a", "ap-south-1b"]